version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      nestjs-framework:
        patterns:
          - '@nestjs/*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
