sonar.projectKey=utkarshutt2706_expense-splitter-api
sonar.organization=utkarshutt2706
sonar.sources=src
sonar.exclusions=src/**/*.spec.ts,src/**/*.e2e-spec.ts,test/**
sonar.coverage.exclusions=src/main.ts,src/**/*.module.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
